name: Deploy Staging Site to Firebase Hosting
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install

      - name: Build Docs
        env:
          NODE_OPTIONS: "--max_old_space_size=7168"
        run: npm run docs:build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SA_VITEPRESS_DOCS }}'
          channelId: stage
